[package]
name = "betrayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target."cfg(target_os = \"windows\")".dependencies]
once_cell = "1"
windows = { version = "0.51", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_System_SystemServices",
    "Win32_Graphics_Gdi"
]}

[target."cfg(target_os = \"linux\")".dependencies]
zbus = "3"
futures-lite = "1"

[target."cfg(target_os = \"macos\")".dependencies]
system_status_bar_macos = "0.1.3"
block2 = "0.3"
icrate = { version = "0.0.4", features = ["apple", "Foundation_all", "AppKit_all"] }
objc2 = "0.4"