[package]
name = "betrayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"

[target."cfg(target_os = \"windows\")".dependencies]
once_cell = "1"
windows = { version = "0.51", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_System_SystemServices",
    "Win32_Graphics_Gdi"
]}

[target."cfg(target_os = \"linux\")".dependencies]
zbus = "3"
async-io = "1"
parking_lot = "0.12"
flume = "0.11"
png = "0.17"

[target."cfg(target_os = \"macos\")".dependencies]
system_status_bar_macos = "0.1.3"
block2 = "0.3"
icrate = { version = "0.0.4", features = ["apple", "Foundation_all", "AppKit_all"] }
objc2 = "0.4"

[dev-dependencies]
winit = "0.29"
simple_logger = { version = "4", default-features = false }
anyhow = "1"